import { useEffect, useState } from 'react'
import PageHeader from '../components/PageHeader'
import { adminApi } from '../api/adminApi'
import { useAdmin } from '../context/AdminContext'
import Pagination from '../components/Pagination'

const date = (value) => new Date(value).toLocaleString('en-RW', { dateStyle: 'medium', timeStyle: 'short' })

export default function VideosPage() {
  const { session } = useAdmin(); const [filter, setFilter] = useState('pending'); const [videos, setVideos] = useState([]); const [pagination, setPagination] = useState(null); const [page, setPage] = useState(1); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState('')
  const load = async () => { try { const result = await adminApi.videos(filter, page, session.token); setVideos(result.videos); setPagination(result.pagination) } catch (error) { setNotice(error.message) } }
  useEffect(() => { setPage(1) }, [filter])
  useEffect(() => { load() }, [filter, page])
  const review = async (id, status) => { setBusy(id); try { await adminApi.reviewVideo(id, status, session.token); setNotice(`Video ${status}.`); await load() } catch (error) { setNotice(error.message) } finally { setBusy('') } }
  const resetViews = async (id) => { if (!window.confirm('Reset this video views to 0?')) return; setBusy(id); try { await adminApi.resetVideoViews(id, session.token); setNotice('Video views reset to 0.'); await load() } catch (error) { setNotice(error.message) } finally { setBusy('') } }
  return <><PageHeader eyebrow="Control room / content" title="Video moderation" description="Publish, pause, resume, or archive uploaded videos." onRefresh={load} />{notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>Dismiss</button></div>}<section className="panel page-panel"><div className="panel-heading"><div><span className="eyebrow">Content queue</span><h2>Uploaded videos</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="pending">Needs review</option><option value="active">Published</option><option value="paused">Paused</option><option value="archived">Archived</option></select></div>{videos.length === 0 ? <div className="empty">No {filter} videos.</div> : videos.map((video) => <article className="video-row" key={video._id}><div className="video-thumb">{video.thumbnailUrl ? <img src={video.thumbnailUrl} alt="" /> : <span>VIDEO</span>}</div><div className="video-main"><strong>{video.videoTitle}</strong><p>{video.user?.username || 'Unknown creator'} · {video.channel?.channelName || 'No channel'}</p><small>{date(video.createdAt)} · {video.category} · {video.views.toLocaleString()} views</small></div><span className={`status ${video.status}`}>{video.status}</span><div className="video-actions">{video.status === 'pending' && <button className="approve" disabled={busy === video._id} onClick={() => review(video._id, 'active')}>Publish</button>}{video.status === 'active' && <button className="pause" disabled={busy === video._id} onClick={() => review(video._id, 'paused')}>Pause</button>}{video.status === 'paused' && <button className="approve" disabled={busy === video._id} onClick={() => review(video._id, 'active')}>Resume</button>}{video.status !== 'archived' && <button className="reject" disabled={busy === video._id} onClick={() => review(video._id, 'archived')}>Archive</button>}<button className="reset-views" disabled={busy === video._id} onClick={() => resetViews(video._id)}>Reset views</button></div></article>)}<Pagination pagination={pagination} onChange={setPage} /></section></>
}
